AnimalManagement/Models/ErrorViewModel.cs
namespace AnimalManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnimalManagement/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalManagement.Controllers
{
    public class AboutController : Controller
    {
        public ViewResult About()
        {
            return View();
        }

        
    }
}

AnimalManagement/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalManagement.Controllers
{
    public class AuthController : Controller
    {
        public ViewResult Login()
        {
            return View();
        }

        public ViewResult Signup()
        {
            return View();
        }
    }
}

AnimalManagement/Controllers/HomeController.cs
using AnimalManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AnimalManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
         
        public ViewResult Contact()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AnimalManagement/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalManagement.Controllers
{
    public class ServicesController : Controller
    {
        
        public ViewResult Index()
        {
            return View();
        }
        
        public ViewResult Adopt()
        {
            return View();
        }

        public ViewResult Donate()
        {
            return View();
        }
    }
}

AnimalManagement/Controllers/WhatWeDoController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalManagement.Controllers
{
    public class WhatWeDoController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

AnimalManagement/Views/About/About.cshtml
@{
    ViewData["Title"] = "About Us";
}



<style>

    .about_us{
        position: absolute;
        top: 10%;
        left: 40%;
        background-color: #e26318;
        padding: 20px;
        font-size: 40px;
        font-weight: bold;    
        border-radius: 10px;
    }


    .h_text{
        color: #e26318;
        font-size: 40px;
    }
</style>

<div class="container-fluid">
    <img src="~/images/about_1.jpg" style="width: 1200px; height: 600px"/>

    <!--About US-->
    <div class="about_us" stlye="widhth: 100%">
        <p class="text-center">ABOUT US</p>
    </div>

    <div class="history_text">
        <span class="h_text">
        History
    </span>

    <p>
    The Kathmandu Animal Treatment Centre (KAT Centre) was first envisioned after Jan Salter, the founder of KAT, visited the organization “Help in Suffering” in Jaipur, India.
    Impressed with the way this and other animal welfare organizations have managed difficult street dog problems and eliminated rabies through Animal Birth Control (ABC) and widespread rabies vaccinations, Jan came back to Nepal convinced that Kathmandu, Nepal could also become a rabies-free, dog-friendly city.
    The KAT Centre was registered as a non-profit, charitable animal welfare organisation in 2003. KAT officially opened its doors on 9 May 2004 and it has grown steadily since then. As we have grown, our location has changed several times, but the founding principals and our work remain the same:
    </p>

    <ol>
        <li>To rescue and treat sick and injured animals living on the streets of Kathmandu.</li>
        <li>To lower the street dog (and cat) population by spaying and neutering.</li>
        <li>To reduce the incidence of rabies and other viruses through vaccination and education.</li>
    </ol>

    <p>Our site is based on its own land, giving us security for the future and the freedom to continue expanding our facilities when the opportunity arises.

We are constantly looking ahead and developing our long term strategy for the continued management and protection of the street animals of Kathmandu.</p>

    </div>

</div>

AnimalManagement/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

<div class="container">
    <div class="row">
        <div class="col">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14134.065952909976!2d85.32395955!3d27.670427399999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2snp!4v1655797766792!5m2!1sen!2snp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <div class="col">
            <div class="mb-3">
     <label for="name" class="form-label">Name</label>
    <input type="email" class="form-control" id="name">
    </div>
            <div class="mb-3">
     <label for="email" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email">
    </div>
    <div class="mb-3">
    <label for="message" class="form-label">Message</label>
    <textarea class="form-control" id="Message" rows="3"></textarea>
    </div>
    <button type="button" class="btn btn-success">
        Send
    </button>
        </div>
    </div>
</div>

AnimalManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container-fluid">
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/img2.jpg" class="d-block w-100" alt="dog">
    </div>
    <div class="carousel-item">
      <img src="~/images/img6.jpg" class="d-block w-100" alt="cow">
    </div>
    <div class="carousel-item">
      <img src="~/images/img7.jpg" class="d-block w-100" alt="inject">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!--First Row-->
  <div class="row mt-5">
    <div class="col">
      <img src="~/images/img1.jpg" />
    </div>
    <div class="col">
      <span style="color: #e26318; font-size: 25px" class="text-center">We rescue helpless animals in their hour of need</span>
       <p class="mt-5" style="font-size: 20px">Every day our ambulance collects critically sick and injured animals, bringing them back to our vets for emergency treatment and love and care.</p>  
  </div>
    </div>

    <!--Second Row-->
    <div class="row mt-5">
    <div class="col">
      <span style="color: #e26318; font-size: 25px" class="text-center">We deliver effective solutions to the street dogs population crisis</span>
       <p class="mt-5" style="font-size: 20px">Informed by cuting edge science and with animal welfare in mind, we are humanly managing the street dog population of Nepal.</p>  
  </div>
  <div class="col">
      <img src="~/images/img1.jpg" />
    </div>
    </div>

    <!--Third Row-->
    <div class="row mt-5">
    <div class="col">
      <img src="~/images/img1.jpg" />
    </div>
    <div class="col">
      <span style="color: #e26318; font-size: 25px" class="text-center">We're defeating one of the world's most deadly diseases.</span>
       <p class="mt-5" style="font-size: 20px">Rabies has been bringing terror to the heart of mankind for millennia and still claims thousands of fatalities each year. We're working to defeat it.</p>  
  </div>
    </div>
    <hr />
<!--Fourth Row-->
      <div class="row">
    <div class="col">
      <div class="card" style="width: 18rem;">
  <img src="~/images/dog_1.jpg" class="card-img-top" alt="">
  <div class="card-body">
    <a href="#" class="btn btn-primary">DONATE</a>
  </div>
</div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem;">
  <img src="~/images/dog_2.jpg" class="card-img-top" alt="">
  <div class="card-body">
    <a href="#" class="btn btn-primary">ADOPT</a>
  </div>
</div>
    </div>
  </div>
</div>    

AnimalManagement/Views/Services/Adopt.cshtml
@{
    ViewData["Title"] = "Adopt";
}

<div class="container">
  <div class="row">
    <div class="col">
      <div class="card" style="width: 18rem;">
     <img class="card-img-top" src="~/images/dog_1.jpg" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-text">Rocky</h5>
    <h5 class="card-text">Sex: Male</h5>
    <h5 class="card-text">Estimated Age: 5 months</h5>
    </div>
    </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem;">
     <img class="card-img-top" src="~/images/dog_1.jpg" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-text">Rocky</h5>
    <h5 class="card-text">Sex: Male</h5>
    <h5 class="card-text">Estimated Age: 5 months</h5>
    </div>
    </div>    </div>
    <div class="col">
      <div class="card" style="width: 18rem;">
     <img class="card-img-top" src="~/images/dog_1.jpg" alt="Card image cap">
    <div class="card-body">
    <h5 class="card-text">Rocky</h5>
    <h5 class="card-text">Sex: Male</h5>
    <h5 class="card-text">Estimated Age: 5 months</h5>
    </div>
    </div>
    </div>
  </div>




  <!--Form-->
  <hr />
  <h1 class="mt-5">Fill form about the animal to begin adoption process</h1>
  <form>
  <div class="form-group mb-3">
    <label for="email">Your Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    
  </div>
  <div class="form-group mb-3">
    <label for="name">Your Name</label>
    <input type="text" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group mb-3">
    <label for="name">Dog Name</label>
    <input type="text" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group mb-3">
    <label for="name">Dog Breed</label>
    <input type="text" class="form-control" id="exampleInputPassword1">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>

AnimalManagement/Views/Services/Donate.cshtml
@{

    ViewData["Title"] = "Donate";
}

<style>


    .donate_img{
        border: 1px solid black;
        border-radius: 10px;
        padding: 20px;
        transition: 0.5s ease;
        margin-left: 15px;
    }
    .donate_img:hover{
        background-color: #e26318;
    }

</style>

<div class="container">
<h1 class="mt-5">Thank you for choosing to donate us</h1>
  <form>
  <div class="form-group mb-3">
    <label for="email">Your Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    
  </div>
  <div class="form-group mb-3">
    <label for="name">Your Name</label>
    <input type="text" class="form-control" id="exampleInputPassword1">
  </div>
  <h1>Donate Via</h1>
  <div class="row">
      <div class="col donate_img text-center">
      <a href="#"><img src="~/images/esewa_bg.png" style="height: 80px"/></a></div>
      <div class="col donate_img text-center">
      <a href="#" class="esewa_img"><img src="~/images/khalti_bg.png" style="height: 80px"/></a>
    </div>
  </div>
  
  
</form>
</div>

AnimalManagement/Views/Services/Index.cshtml
@{
}

<div class="container">
    <h1>You Can help us in</h1>
  <div class="row text-center mt-5">
    <a asp-controller="Services" asp-action="adopt" style="text-decoration: none; color: black;">
      <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Adopt</h1>
      <i class="fa-solid fa-paw" style="font-size: 40px"></i>
    </div>
    </a>
    
    <a asp-controller="Services" asp-action="donate" style="text-decoration: none; color: black;">
    <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Donate</h1>
      <i class="fa-solid fa-hand-holding-medical" style="font-size: 40px"></i>
    </div>
    </a>
</div>
</div>

AnimalManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AnimalManagement.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/26e345a139.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnimalManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WhatWeDo" asp-action="Index">What We Do</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">How You Can Help!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        &nbsp;
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Auth" asp-action="Signup">Sign Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - AnimalManagement
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AnimalManagement/Views/WhatWeDo/Index.cshtml
@{
    ViewData["Title"] = "What we do";
}

<div class="container">
    <h1>Here are the some of the things that we provide</h1>
  <div class="row text-center mt-5">
    <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Animal Birth Control</h1>
      <i class="fa-solid fa-dog" style="font-size: 40px"></i>
    </div>
    
    <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Rescue and Treatment</h1>
      <i class="fa-solid fa-capsules" style="font-size: 40px"></i>
    </div>

     <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Rabies Prevention</h1>
      <i class="fa-solid fa-syringe" style="font-size: 40px"></i>
    </div>
    </div>
    




    <div class="row text-center mt-5">
    <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Education and Awareness</h1>
      <i class="fa-solid fa-award" style="font-size: 40px"></i>
    </div>
    
    <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Street Animal Feeding</h1>
      <i class="fa-solid fa-bowl-food" style="font-size: 40px"></i>
    </div>

     <div class="col m-4" style="background-color: #e26318; border-radius: 10px; padding: 20px;">
        <h1>Annual Vaccination</h1>
      <i class="fa-solid fa-briefcase-medical" style="font-size: 40px"></i>
    </div>
    </div>


  </div>